#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: ab27b0e
#
Name     : R-optparse
Version  : 1.7.4
Release  : 55
URL      : https://cran.r-project.org/src/contrib/optparse_1.7.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/optparse_1.7.4.tar.gz
Summary  : Command Line Option Parser
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: R-optparse-license = %{version}-%{release}
Requires: R-getopt
BuildRequires : R-getopt
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
be used with Rscript to write "#!" shebang scripts that accept short and
    long flag/options.

%package license
Summary: license components for the R-optparse package.
Group: Default

%description license
license components for the R-optparse package.


%prep
%setup -q -n optparse
pushd ..
cp -a optparse buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1705422423

%install
export SOURCE_DATE_EPOCH=1705422423
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-optparse
cp %{_builddir}/optparse/COPYING %{buildroot}/usr/share/package-licenses/R-optparse/b47456e2c1f38c40346ff00db976a2badf36b5e3 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/optparse/COPYRIGHTS
/usr/lib64/R/library/optparse/DESCRIPTION
/usr/lib64/R/library/optparse/INDEX
/usr/lib64/R/library/optparse/Meta/Rd.rds
/usr/lib64/R/library/optparse/Meta/features.rds
/usr/lib64/R/library/optparse/Meta/hsearch.rds
/usr/lib64/R/library/optparse/Meta/links.rds
/usr/lib64/R/library/optparse/Meta/nsInfo.rds
/usr/lib64/R/library/optparse/Meta/package.rds
/usr/lib64/R/library/optparse/Meta/vignette.rds
/usr/lib64/R/library/optparse/NAMESPACE
/usr/lib64/R/library/optparse/NEWS.md
/usr/lib64/R/library/optparse/R/optparse
/usr/lib64/R/library/optparse/R/optparse.rdb
/usr/lib64/R/library/optparse/R/optparse.rdx
/usr/lib64/R/library/optparse/doc/index.html
/usr/lib64/R/library/optparse/doc/optparse.R
/usr/lib64/R/library/optparse/doc/optparse.Rrst
/usr/lib64/R/library/optparse/doc/optparse.html
/usr/lib64/R/library/optparse/exec/display_file.R
/usr/lib64/R/library/optparse/exec/example.R
/usr/lib64/R/library/optparse/help/AnIndex
/usr/lib64/R/library/optparse/help/aliases.rds
/usr/lib64/R/library/optparse/help/figures/logo.png
/usr/lib64/R/library/optparse/help/figures/logo.svg
/usr/lib64/R/library/optparse/help/optparse.rdb
/usr/lib64/R/library/optparse/help/optparse.rdx
/usr/lib64/R/library/optparse/help/paths.rds
/usr/lib64/R/library/optparse/html/00Index.html
/usr/lib64/R/library/optparse/html/R.css
/usr/lib64/R/library/optparse/tests/run-all.R
/usr/lib64/R/library/optparse/tests/test_help.R
/usr/lib64/R/library/optparse/tests/test_help.Rout.save
/usr/lib64/R/library/optparse/tests/testthat/test-optparse.R

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-optparse/b47456e2c1f38c40346ff00db976a2badf36b5e3
